In [1]:
import kagglehub
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
os.environ['KAGGLEHUB_CACHE'] = '/'

In [2]:
path = kagglehub.dataset_download("nphantawee/pump-sensor-data")

print("Path to dataset files:", path)

Path to dataset files: /datasets\nphantawee\pump-sensor-data\versions\1

In [3]:
data = pd.read_csv("/datasets/nphantawee/pump-sensor-data/versions/1/sensor.csv")

In [4]:
data.head(10)

,Unnamed: 0,timestamp,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,...,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
0,0,2018-04-01 00:00:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
1,1,2018-04-01 00:01:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
2,2,2018-04-01 00:02:00,2.444734,47.35243,53.2118,46.397570,638.8889,73.54598,13.32465,16.03733,...,41.66666,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,241.3194,203.7037,NORMAL
3,3,2018-04-01 00:03:00,2.460474,47.09201,53.1684,46.397568,628.1250,76.98898,13.31742,16.24711,...,40.88541,39.062500,64.81481,51.21528,38.194440,155.9606,66.84028,240.4514,203.1250,NORMAL
4,4,2018-04-01 00:04:00,2.445718,47.13541,53.2118,46.397568,636.4583,76.58897,13.35359,16.21094,...,41.40625,38.773150,65.10416,51.79398,38.773150,158.2755,66.55093,242.1875,201.3889,NORMAL
5,5,2018-04-01 00:05:00,2.453588,47.09201,53.1684,46.397568,637.6157,78.18568,13.41146,16.16753,...,42.70833,38.773150,63.65741,51.79398,38.773150,164.6412,66.55093,241.6088,201.6782,NORMAL
6,6,2018-04-01 00:06:00,2.455556,47.04861,53.1684,46.397568,633.3333,75.81614,13.43316,16.13136,...,43.22916,38.194440,61.92130,51.79398,39.062500,171.8750,67.70834,240.1620,200.2315,NORMAL
7,7,2018-04-01 00:07:00,2.449653,47.13541,53.1684,46.397568,630.6713,75.77331,13.25231,16.12413,...,42.96875,38.194443,59.60648,50.92593,39.351850,178.5301,68.57639,241.3194,201.0995,NORMAL
8,8,2018-04-01 00:08:00,2.463426,47.09201,53.1684,46.397568,631.9444,74.58916,13.28848,16.13136,...,42.18750,38.194440,57.87037,50.63657,39.351850,182.0023,69.44444,243.0556,201.6782,NORMAL
9,9,2018-04-01 00:09:00,2.445718,47.17882,53.1684,46.397568,641.7823,74.57428,13.38252,16.24711,...,41.66666,39.062500,56.42361,50.63657,39.062500,186.6319,69.73380,246.5278,200.8102,NORMAL

In [5]:
data.isna().sum()

Unnamed: 0             0
timestamp              0
sensor_00          10208
sensor_01            369
sensor_02             19
sensor_03             19
sensor_04             19
sensor_05             19
sensor_06           4798
sensor_07           5451
sensor_08           5107
sensor_09           4595
sensor_10             19
sensor_11             19
sensor_12             19
sensor_13             19
sensor_14             21
sensor_15         220320
sensor_16             31
sensor_17             46
sensor_18             46
sensor_19             16
sensor_20             16
sensor_21             16
sensor_22             41
sensor_23             16
sensor_24             16
sensor_25             36
sensor_26             20
sensor_27             16
sensor_28             16
sensor_29             72
sensor_30            261
sensor_31             16
sensor_32             68
sensor_33             16
sensor_34             16
sensor_35             16
sensor_36             16
sensor_37             16
sensor_38             27
sensor_39             27
sensor_40             27
sensor_41             27
sensor_42             27
sensor_43             27
sensor_44             27
sensor_45             27
sensor_46             27
sensor_47             27
sensor_48             27
sensor_49             27
sensor_50          77017
sensor_51          15383
machine_status         0
dtype: int64

In [6]:
data.rename(columns={"Unnamed: 0": "operation_no"}, inplace=True)

In [7]:
data.set_index('operation_no', inplace=True)

In [8]:
data.head(10)

,timestamp,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,...,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
operation_no,,,,,,,,,,,,,,,,,,,,,
0,2018-04-01 00:00:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
1,2018-04-01 00:01:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
2,2018-04-01 00:02:00,2.444734,47.35243,53.2118,46.397570,638.8889,73.54598,13.32465,16.03733,15.61777,...,41.66666,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,241.3194,203.7037,NORMAL
3,2018-04-01 00:03:00,2.460474,47.09201,53.1684,46.397568,628.1250,76.98898,13.31742,16.24711,15.69734,...,40.88541,39.062500,64.81481,51.21528,38.194440,155.9606,66.84028,240.4514,203.1250,NORMAL
4,2018-04-01 00:04:00,2.445718,47.13541,53.2118,46.397568,636.4583,76.58897,13.35359,16.21094,15.69734,...,41.40625,38.773150,65.10416,51.79398,38.773150,158.2755,66.55093,242.1875,201.3889,NORMAL
5,2018-04-01 00:05:00,2.453588,47.09201,53.1684,46.397568,637.6157,78.18568,13.41146,16.16753,15.89265,...,42.70833,38.773150,63.65741,51.79398,38.773150,164.6412,66.55093,241.6088,201.6782,NORMAL
6,2018-04-01 00:06:00,2.455556,47.04861,53.1684,46.397568,633.3333,75.81614,13.43316,16.13136,15.65393,...,43.22916,38.194440,61.92130,51.79398,39.062500,171.8750,67.70834,240.1620,200.2315,NORMAL
7,2018-04-01 00:07:00,2.449653,47.13541,53.1684,46.397568,630.6713,75.77331,13.25231,16.12413,16.19647,...,42.96875,38.194443,59.60648,50.92593,39.351850,178.5301,68.57639,241.3194,201.0995,NORMAL
8,2018-04-01 00:08:00,2.463426,47.09201,53.1684,46.397568,631.9444,74.58916,13.28848,16.13136,15.47309,...,42.18750,38.194440,57.87037,50.63657,39.351850,182.0023,69.44444,243.0556,201.6782,NORMAL
9,2018-04-01 00:09:00,2.445718,47.17882,53.1684,46.397568,641.7823,74.57428,13.38252,16.24711,15.61777,...,41.66666,39.062500,56.42361,50.63657,39.062500,186.6319,69.73380,246.5278,200.8102,NORMAL

In [9]:
data['time'] = pd.to_datetime(data.pop('timestamp')).dt.time

In [10]:
data.head(10)

,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,sensor_09,...,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status,time
operation_no,,,,,,,,,,,,,,,,,,,,,
0,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,15.05353,...,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL,00:00:00
1,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,15.05353,...,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL,00:01:00
2,2.444734,47.35243,53.2118,46.397570,638.8889,73.54598,13.32465,16.03733,15.61777,15.01013,...,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,241.3194,203.7037,NORMAL,00:02:00
3,2.460474,47.09201,53.1684,46.397568,628.1250,76.98898,13.31742,16.24711,15.69734,15.08247,...,39.062500,64.81481,51.21528,38.194440,155.9606,66.84028,240.4514,203.1250,NORMAL,00:03:00
4,2.445718,47.13541,53.2118,46.397568,636.4583,76.58897,13.35359,16.21094,15.69734,15.08247,...,38.773150,65.10416,51.79398,38.773150,158.2755,66.55093,242.1875,201.3889,NORMAL,00:04:00
5,2.453588,47.09201,53.1684,46.397568,637.6157,78.18568,13.41146,16.16753,15.89265,15.16204,...,38.773150,63.65741,51.79398,38.773150,164.6412,66.55093,241.6088,201.6782,NORMAL,00:05:00
6,2.455556,47.04861,53.1684,46.397568,633.3333,75.81614,13.43316,16.13136,15.65393,15.08247,...,38.194440,61.92130,51.79398,39.062500,171.8750,67.70834,240.1620,200.2315,NORMAL,00:06:00
7,2.449653,47.13541,53.1684,46.397568,630.6713,75.77331,13.25231,16.12413,16.19647,15.08247,...,38.194443,59.60648,50.92593,39.351850,178.5301,68.57639,241.3194,201.0995,NORMAL,00:07:00
8,2.463426,47.09201,53.1684,46.397568,631.9444,74.58916,13.28848,16.13136,15.47309,15.11863,...,38.194440,57.87037,50.63657,39.351850,182.0023,69.44444,243.0556,201.6782,NORMAL,00:08:00
9,2.445718,47.17882,53.1684,46.397568,641.7823,74.57428,13.38252,16.24711,15.61777,15.11863,...,39.062500,56.42361,50.63657,39.062500,186.6319,69.73380,246.5278,200.8102,NORMAL,00:09:00

In [11]:
data.insert(0, 'time', data.pop('time'))
data.head(30)

,time,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,...,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
operation_no,,,,,,,,,,,,,,,,,,,,,
0,00:00:00,2.465394,47.09201,53.21180,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
1,00:01:00,2.465394,47.09201,53.21180,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
2,00:02:00,2.444734,47.35243,53.21180,46.397570,638.8889,73.54598,13.32465,16.03733,15.61777,...,41.66666,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,241.3194,203.7037,NORMAL
3,00:03:00,2.460474,47.09201,53.16840,46.397568,628.1250,76.98898,13.31742,16.24711,15.69734,...,40.88541,39.062500,64.81481,51.21528,38.194440,155.9606,66.84028,240.4514,203.1250,NORMAL
4,00:04:00,2.445718,47.13541,53.21180,46.397568,636.4583,76.58897,13.35359,16.21094,15.69734,...,41.40625,38.773150,65.10416,51.79398,38.773150,158.2755,66.55093,242.1875,201.3889,NORMAL
5,00:05:00,2.453588,47.09201,53.16840,46.397568,637.6157,78.18568,13.41146,16.16753,15.89265,...,42.70833,38.773150,63.65741,51.79398,38.773150,164.6412,66.55093,241.6088,201.6782,NORMAL
6,00:06:00,2.455556,47.04861,53.16840,46.397568,633.3333,75.81614,13.43316,16.13136,15.65393,...,43.22916,38.194440,61.92130,51.79398,39.062500,171.8750,67.70834,240.1620,200.2315,NORMAL
7,00:07:00,2.449653,47.13541,53.16840,46.397568,630.6713,75.77331,13.25231,16.12413,16.19647,...,42.96875,38.194443,59.60648,50.92593,39.351850,178.5301,68.57639,241.3194,201.0995,NORMAL
8,00:08:00,2.463426,47.09201,53.16840,46.397568,631.9444,74.58916,13.28848,16.13136,15.47309,...,42.18750,38.194440,57.87037,50.63657,39.351850,182.0023,69.44444,243.0556,201.6782,NORMAL
9,00:09:00,2.445718,47.17882,53.16840,46.397568,641.7823,74.57428,13.38252,16.24711,15.61777,...,41.66666,39.062500,56.42361,50.63657,39.062500,186.6319,69.73380,246.5278,200.8102,NORMAL
10,00:10:00,2.464410,47.48264,53.12500,46.397568,637.7314,76.05148,13.41146,16.16753,15.65393,...,41.40625,39.351850,54.97685,50.92593,39.351850,190.9722,71.18056,250.8681,199.9421,NORMAL
11,00:11:00,2.444734,47.91666,53.16840,46.397568,635.6482,74.58654,13.41146,16.16753,15.84925,...,41.66666,39.351852,53.81944,51.21528,39.062500,193.5764,72.33796,253.1829,200.2315,NORMAL
12,00:12:00,2.460474,48.26389,53.12500,46.397568,630.0926,76.95988,13.34635,16.16753,15.73351,...,42.70833,39.351850,53.24074,50.92593,39.062500,195.6019,72.33796,253.1829,202.2569,NORMAL
13,00:13:00,2.448669,48.43750,53.16840,46.397568,638.6574,75.67310,13.31742,16.16753,15.84925,...,42.70833,40.509260,53.81944,50.63657,39.062500,196.4699,72.91666,252.8935,202.8356,NORMAL
14,00:14:00,2.453588,48.56771,53.16840,46.397568,632.4074,80.65949,13.38976,16.13136,15.53096,...,42.18750,41.666670,53.53009,50.34722,39.062500,205.4398,72.91666,252.0255,201.0995,NORMAL
15,00:15:00,2.455556,48.39410,53.12500,46.397570,642.3611,78.13193,13.35359,16.21094,15.45139,...,41.66666,42.534720,52.66204,49.76852,39.062500,217.0139,73.78472,253.7616,198.7847,NORMAL
16,00:16:00,2.449653,48.39410,53.16840,46.310760,630.2084,77.89381,13.30295,16.16753,15.89265,...,40.88541,43.981480,52.37268,48.90046,39.351850,229.1667,74.94213,251.7361,197.9167,NORMAL
17,00:17:00,2.463426,48.48090,53.68924,46.310760,643.6343,77.30572,13.34635,16.16753,15.61777,...,40.62500,43.981480,52.37268,47.74306,39.351850,239.2940,74.36343,246.5278,198.4954,NORMAL
18,00:18:00,2.445718,48.61111,53.12500,46.310760,632.9861,76.66199,13.34635,16.21094,15.81308,...,40.62500,43.402780,52.08333,46.29630,40.219910,240.4514,73.49537,241.6088,198.4954,NORMAL
19,00:19:00,2.464410,48.61111,53.16840,46.310760,644.3287,78.49116,13.34635,16.13136,15.70457,...,40.62500,42.245370,52.08333,44.84954,40.509260,234.3750,72.91666,236.9792,197.9167,NORMAL
20,00:20:00,2.445718,49.08854,53.03819,46.310760,633.4491,76.95741,13.34635,16.16753,15.76968,...,40.36458,41.666670,53.53009,43.69213,40.509260,221.3542,76.67824,236.9792,198.7847,NORMAL
21,00:21:00,2.460474,49.21875,53.12500,46.310760,626.2731,78.76208,13.34635,16.16753,15.45139,...,40.10416,40.798610,54.10880,43.11343,40.219910,211.5162,83.04398,240.1620,201.3889,NORMAL
22,00:22:00,2.448669,48.78472,53.12500,46.267360,635.4166,76.26164,13.41146,16.21094,15.65393,...,39.58333,40.219910,53.24074,42.53472,40.219906,210.0694,87.96296,243.6343,204.5718,NORMAL
23,00:23:00,2.453588,49.08854,53.16840,46.267361,635.4166,79.25443,13.34635,16.21094,15.81308,...,39.06250,39.351850,51.79398,43.40278,40.219910,210.0694,92.30324,244.7917,208.3333,NORMAL
24,00:24:00,2.453588,49.21875,53.03819,46.267361,634.3750,76.88760,13.31742,16.12413,15.77691,...,39.06250,38.773148,50.63657,43.98148,39.641200,207.4653,96.93287,243.3449,210.9375,NORMAL
25,00:25:00,2.449653,49.30555,53.16840,46.267361,634.9537,75.76706,13.34635,16.16030,15.69734,...,38.28125,38.194440,49.47917,45.42824,39.641200,206.0185,100.11570,244.7917,211.5162,NORMAL
26,00:26:00,2.459491,49.08854,53.16840,46.267361,632.4074,75.63688,13.28848,16.12413,15.76968,...,38.28125,38.194440,48.32176,46.87500,40.219910,203.7037,101.85190,244.5023,212.3843,NORMAL
27,00:27:00,2.448669,48.78472,53.12500,46.267361,639.2361,75.62278,13.49826,16.13136,15.69734,...,38.80208,37.905090,47.45370,48.03241,40.509260,201.0995,103.00930,246.5278,214.6991,NORMAL
28,00:28:00,2.464410,48.35069,53.16840,46.267360,641.3195,75.83797,13.41869,16.16030,15.65393,...,39.32291,37.615740,46.29630,49.18982,40.509260,198.4954,102.43060,249.1319,215.5671,NORMAL
29,00:29:00,2.444734,48.04688,53.12500,46.223960,635.4166,73.64476,13.28848,16.21094,16.31944,...,40.88541,37.615740,45.13889,49.47917,40.798610,196.7593,103.00930,250.5787,216.7245,NORMAL

In [12]:
data.drop(['sensor_00', 'sensor_15', 'sensor_50', 'sensor_51'], axis=1, inplace=True)
data.head(10)

,time,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,sensor_09,...,sensor_41,sensor_42,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,machine_status
operation_no,,,,,,,,,,,,,,,,,,,,,
0,00:00:00,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,15.05353,...,30.989580,31.770832,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,NORMAL
1,00:01:00,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,15.05353,...,30.989580,31.770832,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,NORMAL
2,00:02:00,47.35243,53.2118,46.397570,638.8889,73.54598,13.32465,16.03733,15.61777,15.01013,...,30.468750,31.770830,41.66666,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,NORMAL
3,00:03:00,47.09201,53.1684,46.397568,628.1250,76.98898,13.31742,16.24711,15.69734,15.08247,...,30.468750,31.510420,40.88541,39.062500,64.81481,51.21528,38.194440,155.9606,66.84028,NORMAL
4,00:04:00,47.13541,53.2118,46.397568,636.4583,76.58897,13.35359,16.21094,15.69734,15.08247,...,30.989580,31.510420,41.40625,38.773150,65.10416,51.79398,38.773150,158.2755,66.55093,NORMAL
5,00:05:00,47.09201,53.1684,46.397568,637.6157,78.18568,13.41146,16.16753,15.89265,15.16204,...,30.989580,31.250000,42.70833,38.773150,63.65741,51.79398,38.773150,164.6412,66.55093,NORMAL
6,00:06:00,47.04861,53.1684,46.397568,633.3333,75.81614,13.43316,16.13136,15.65393,15.08247,...,31.250000,31.510420,43.22916,38.194440,61.92130,51.79398,39.062500,171.8750,67.70834,NORMAL
7,00:07:00,47.13541,53.1684,46.397568,630.6713,75.77331,13.25231,16.12413,16.19647,15.08247,...,30.989580,31.510416,42.96875,38.194443,59.60648,50.92593,39.351850,178.5301,68.57639,NORMAL
8,00:08:00,47.09201,53.1684,46.397568,631.9444,74.58916,13.28848,16.13136,15.47309,15.11863,...,30.989582,31.510416,42.18750,38.194440,57.87037,50.63657,39.351850,182.0023,69.44444,NORMAL
9,00:09:00,47.17882,53.1684,46.397568,641.7823,74.57428,13.38252,16.24711,15.61777,15.11863,...,30.989582,31.510416,41.66666,39.062500,56.42361,50.63657,39.062500,186.6319,69.73380,NORMAL

In [13]:
data.isna().sum()

time                 0
sensor_01          369
sensor_02           19
sensor_03           19
sensor_04           19
sensor_05           19
sensor_06         4798
sensor_07         5451
sensor_08         5107
sensor_09         4595
sensor_10           19
sensor_11           19
sensor_12           19
sensor_13           19
sensor_14           21
sensor_16           31
sensor_17           46
sensor_18           46
sensor_19           16
sensor_20           16
sensor_21           16
sensor_22           41
sensor_23           16
sensor_24           16
sensor_25           36
sensor_26           20
sensor_27           16
sensor_28           16
sensor_29           72
sensor_30          261
sensor_31           16
sensor_32           68
sensor_33           16
sensor_34           16
sensor_35           16
sensor_36           16
sensor_37           16
sensor_38           27
sensor_39           27
sensor_40           27
sensor_41           27
sensor_42           27
sensor_43           27
sensor_44           27
sensor_45           27
sensor_46           27
sensor_47           27
sensor_48           27
sensor_49           27
machine_status       0
dtype: int64

In [15]:
data['machine_status'].value_counts()

machine_status
NORMAL        205836
RECOVERING     14477
BROKEN             7
Name: count, dtype: int64

In [16]:
sensors = [c for c in data.columns if c.startswith("sensor_")]
data.loc[data[sensors].isna().any(axis=1), "machine_status"].value_counts()

machine_status
RECOVERING    6080
NORMAL         769
Name: count, dtype: int64

In [25]:
data[sensors].dtypes

sensor_01    float64
sensor_02    float64
sensor_03    float64
sensor_04    float64
sensor_05    float64
sensor_06    float64
sensor_07    float64
sensor_08    float64
sensor_09    float64
sensor_10    float64
sensor_11    float64
sensor_12    float64
sensor_13    float64
sensor_14    float64
sensor_16    float64
sensor_17    float64
sensor_18    float64
sensor_19    float64
sensor_20    float64
sensor_21    float64
sensor_22    float64
sensor_23    float64
sensor_24    float64
sensor_25    float64
sensor_26    float64
sensor_27    float64
sensor_28    float64
sensor_29    float64
sensor_30    float64
sensor_31    float64
sensor_32    float64
sensor_33    float64
sensor_34    float64
sensor_35    float64
sensor_36    float64
sensor_37    float64
sensor_38    float64
sensor_39    float64
sensor_40    float64
sensor_41    float64
sensor_42    float64
sensor_43    float64
sensor_44    float64
sensor_45    float64
sensor_46    float64
sensor_47    float64
sensor_48    float64
sensor_49    float64
dtype: object

In [26]:
data.loc[data["machine_status"] == "RECOVERING", sensors] = data.loc[data["machine_status"] == "RECOVERING", sensors].fillna(0)

In [27]:
data.loc[data[sensors].isna().any(axis=1), "machine_status"].value_counts()

machine_status
NORMAL    769
Name: count, dtype: int64

In [28]:
data.loc[data["machine_status"] == "NORMAL", sensors] = (
    data.loc[data["machine_status"] == "NORMAL", sensors]
    .apply(lambda x: x.fillna(x.mean()), axis=0)
)

data.loc[data[sensors].isna().any(axis=1), "machine_status"].value_counts()

Series([], Name: count, dtype: int64)

In [29]:
data.isna().sum()

time              0
sensor_01         0
sensor_02         0
sensor_03         0
sensor_04         0
sensor_05         0
sensor_06         0
sensor_07         0
sensor_08         0
sensor_09         0
sensor_10         0
sensor_11         0
sensor_12         0
sensor_13         0
sensor_14         0
sensor_16         0
sensor_17         0
sensor_18         0
sensor_19         0
sensor_20         0
sensor_21         0
sensor_22         0
sensor_23         0
sensor_24         0
sensor_25         0
sensor_26         0
sensor_27         0
sensor_28         0
sensor_29         0
sensor_30         0
sensor_31         0
sensor_32         0
sensor_33         0
sensor_34         0
sensor_35         0
sensor_36         0
sensor_37         0
sensor_38         0
sensor_39         0
sensor_40         0
sensor_41         0
sensor_42         0
sensor_43         0
sensor_44         0
sensor_45         0
sensor_46         0
sensor_47         0
sensor_48         0
sensor_49         0
machine_status    0
dtype: int64

In [33]:
data.loc[data["machine_status"] == "RECOVERING", sensors].describe()

,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,sensor_09,sensor_10,...,sensor_40,sensor_41,sensor_42,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49
count,14477.000000,14477.000000,14477.000000,14477.000000,14477.000000,14477.000000,14477.000000,14477.000000,14477.000000,14477.000000,...,14477.000000,14477.000000,14477.000000,14477.000000,14477.000000,14477.000000,14477.000000,14477.000000,14477.000000,14477.000000
mean,39.140109,39.908912,37.843623,93.001962,45.044822,3.873224,5.304695,5.910082,6.030467,1.674465,...,38.565392,32.259359,35.719594,38.921186,32.352484,33.276682,36.055955,34.279970,37.138472,36.484538
std,4.714530,5.179768,3.573667,117.949001,49.427172,4.969801,6.964063,7.116625,7.195243,3.300117,...,37.520525,23.456308,32.334667,32.120810,12.281837,14.323053,22.524935,11.402754,31.811963,23.378234
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,35.373264,36.067707,34.895830,3.336227,0.000000,0.000000,0.000000,0.000000,0.000000,0.245949,...,27.343750,23.437500,25.260420,28.385420,28.645834,28.935180,29.513889,30.381945,29.224537,29.224537
50%,38.671875,38.715270,37.717014,3.567708,0.000000,0.028935,0.036169,0.028935,0.007234,0.357225,...,29.947916,25.781248,28.385416,30.989582,30.671300,30.960650,32.118057,32.986111,31.539352,31.539352
75%,41.015630,42.187500,40.451390,203.029495,99.999878,10.047740,12.579570,12.565100,12.557870,1.909436,...,36.458332,31.249998,32.552082,38.020830,33.275460,33.275463,35.300926,35.879630,35.011574,35.011574
max,53.559020,53.559020,46.701390,611.689800,99.999880,22.251160,23.596640,24.348960,25.000000,58.233810,...,490.104200,420.312500,374.218800,408.593700,361.689800,320.312500,301.504600,303.530100,502.314800,464.409700

In [35]:
data.to_csv("sensors_clean.csv", index=True)

In [36]:
data.loc[data["machine_status"] == "BROKEN", sensors].describe()

,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,sensor_09,sensor_10,...,sensor_40,sensor_41,sensor_42,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,...,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,45.969742,50.837052,42.931546,334.672200,45.351953,9.818328,13.731811,13.294684,12.788318,28.517882,...,118.824397,58.184517,52.715769,64.955347,43.405444,42.080027,55.266200,56.464948,161.168971,60.805228
std,4.167754,3.115010,1.682742,173.963706,31.315537,5.761857,6.073307,5.904074,5.660497,13.339610,...,138.110762,68.367820,54.882430,60.994743,13.206979,11.659190,34.370804,43.470063,127.830219,30.028275
min,40.190970,45.225690,40.190971,200.115738,0.000000,0.028935,0.036169,0.036169,0.007234,2.002474,...,36.718750,23.177082,24.739580,32.291660,28.067130,28.067129,29.513889,29.224537,29.224537,29.513889
25%,43.836805,49.587671,42.122393,201.947327,25.597100,7.277200,15.212670,14.666520,14.330150,26.535315,...,52.994785,30.468745,30.598958,37.630205,34.866895,33.420140,36.313655,38.339120,79.716430,44.704860
50%,45.833332,52.734370,43.402775,206.038757,60.301060,12.304690,15.914350,15.183740,15.053530,28.304880,...,71.614580,35.416660,32.812500,42.708330,37.326390,37.905090,39.062500,43.981480,144.675900,49.768520
75%,47.374135,52.864585,43.663194,460.251724,66.724005,13.827400,16.427955,15.820315,15.100550,36.124165,...,95.052090,37.499995,36.718745,51.041665,51.513965,51.938660,58.883100,45.717590,192.853000,67.708335
max,53.342010,52.994790,45.355900,612.152800,72.520400,14.185470,16.890910,16.869210,15.596060,43.998860,...,427.343700,212.760400,176.822900,202.343700,65.682870,57.870370,127.893500,153.935200,409.143500,121.527800

In [40]:
data[data['machine_status'] == 'BROKEN'].count()

time              7
sensor_01         7
sensor_02         7
sensor_03         7
sensor_04         7
sensor_05         7
sensor_06         7
sensor_07         7
sensor_08         7
sensor_09         7
sensor_10         7
sensor_11         7
sensor_12         7
sensor_13         7
sensor_14         7
sensor_16         7
sensor_17         7
sensor_18         7
sensor_19         7
sensor_20         7
sensor_21         7
sensor_22         7
sensor_23         7
sensor_24         7
sensor_25         7
sensor_26         7
sensor_27         7
sensor_28         7
sensor_29         7
sensor_30         7
sensor_31         7
sensor_32         7
sensor_33         7
sensor_34         7
sensor_35         7
sensor_36         7
sensor_37         7
sensor_38         7
sensor_39         7
sensor_40         7
sensor_41         7
sensor_42         7
sensor_43         7
sensor_44         7
sensor_45         7
sensor_46         7
sensor_47         7
sensor_48         7
sensor_49         7
machine_status    7
dtype: int64